spring:
  application:
    name: shopping-cart

  datasource:
    url: jdbc:mysql://localhost:3306/ecomm?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: my-strong-password

  # JPA settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Okta Security settings
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-yohelt72e38t5w40.us.auth0.com/

server:
  port: 8080